### ISSUE TITLE
Readme and validdations

### ISSUE THREAD

**Issue by warscovich** [guoarthur/Kijiji-Repost-Headless#1]
1.The usage description in the README file is incorrect. Must be done using the command:
" python KijijiCmd.py -u (username) -p (password) [command] "
instead of
" python KijijiCmd.py -u [command]  (username) -p (password) "

2. The minimum size of postAdForm.descriptionfield is 10 characters.

**Comment by guoarthur** [comment]
Thank you for bringing this to my attention. It has been fixed.
