### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by imbkr** [guoarthur/Kijiji-Repost-Headless#15]
I'm seeing a syntax error when I tried to generate a ad,
`18:57:50->python generate_inf_file.py
Traceback (most recent call last):
  File "generate_inf_file.py", line 7, in <module>
    from posting_category import *
  File "/Users/kbonthu/Kijiji-Repost-Headless/kijiji_repost_headless/posting_category.py", line 68
    return {**leafCategory, **(get_category_map(session, newBranches, False))}
             ^
SyntaxError: invalid syntax`

**Comment by guoarthur** [comment]
Can you try upgrading your Python to at least 3.5 and see whether this issue exists?

**Comment by imbkr** [comment]
yep, looks like python3 command is working. Thanks.
