### ISSUE TITLE
Error running generate_inf_file.py

### ISSUE THREAD

**Issue by ge357** [guoarthur/Kijiji-Repost-Headless#19]
george@web64-nginx:~/kijiji_repost_headless$ python3 generate_inf_file.py
Traceback (most recent call last):
  File "generate_inf_file.py", line 7, in <module>
    from posting_category import *
  File "/home/george/kijiji_repost_headless/posting_category.py", line 68
    return {**leafCategory, **(get_category_map(session, newBranches, False))}
             ^
SyntaxError: invalid syntax

**Comment by guoarthur** [comment]
You are likely on the wrong python3 version. Please update to the latest py3 an report back.

**Comment by ge357** [comment]
yes that worked, now I found a few new bugs, when posting a car the year, model and KMs are required fields, the model does not populate correctly and the KMs and year are not asked at all when creating the myadd.inf
this is what worked after manually adding the fields:
postAdForm.priceAmount=15995
postAdForm.attributeMap[noofdoors_s]=5
postAdForm.attributeMap[noofseats_s]=5
postAdForm.attributeMap[carcolor_s]=silver
postAdForm.attributeMap[carmake_s]=nissan
postAdForm.attributeMap[carmodel_s]=juke
postAdForm.attributeMap[carbodytype_s]=suvcrossover
postAdForm.attributeMap[cartrim_s]=SL
postAdForm.attributeMap[cartransmission_s]=2
postAdForm.attributeMap[vehicletype_s]=used
postAdForm.attributeMap[drivetrain_s]=awd
postAdForm.attributeMap[carfueltype_s]=gas
postAdForm.attributeMap[forsaleby_s]=ownr
postAdForm.attributeMap[caryear_i]=2012
postAdForm.attributeMap[carmileageinkms_i]=59000

**Comment by guoarthur** [comment]
Thanks for reporting this. If you're interested, please take a look at fixing this. I believe that the following is a WIP for this exact issue. 

https://github.com/StefGou/Kijiji-Repost-Headless/blob/attributes/kijiji_repost_headless/save_attribute_map_to_json.py

**Comment by guoarthur** [comment]
If you would like to try out a beta version of this, I encourage you to look at this branch:

https://github.com/guoarthur/Kijiji-Repost-Headless/tree/json-attributes

Let me know.
