### ISSUE TITLE
cannot post ads PostAdException(resp.text)

### ISSUE THREAD

**Issue by justinwrightit** [guoarthur/Kijiji-Repost-Headless#23]
When trying to post an ad with & without folder i'm getting the following error:

![image](https://user-images.githubusercontent.com/23126640/27814622-c004cbb2-604b-11e7-9834-824915be3744.png)

I added in the forrentbyhousing_s/furnished_s/petsallowed_s required attributes, not sure what's causing this. I assume it has to do with the category as I did a test in another category & got the ad to post (repost however did not work afterwards - I'll deal with that issue if it comes up again once this is resolved).

I've included the contents of my inf file below, thank you so much.

postAdForm.geocodeLat=43.6381725
postAdForm.geocodeLng=-79.4129782
postAdForm.city=Toronto
postAdForm.province=ON
PostalLat=43.6381725
PostalLng=-79.4129782
categoryId=214
postAdForm.adType=OFFER
postAdForm.priceType=FIXED
postAdForm.priceAmount=1600
postAdForm.attributeMap[numberbathrooms_s]=10
postAdForm.attributeMap[forrentbyhousing_s]=ownr
postAdForm.attributeMap[furnished_s]=0
postAdForm.attributeMap[petsallowed_s]=0
postAdForm.title=1 & 2 Bedroom Condos For Rent!
postAdForm.description=Looking to live in a condo or loft? Send me a message with what you're looking for and I'll be happy to assist you in finding your next home.
postAdForm.locationId=1700273
locationLevel0=1700272
postAdForm.postalCode=M6K 3P9
featuresForm.topAdDuration=7
submitType=saveAndCheckout
imageCsv=tf.jpg,512.jpg,51.jpg,75.jpg,150.jpg,752.jpg,pool.jpg

**Comment by guoarthur** [comment]
Please look at the other issues open. This is a known issue with a known workaround. 

https://github.com/guoarthur/Kijiji-Repost-Headless/issues/11

**Comment by guoarthur** [comment]
If you would like to try out a beta version of this, I encourage you to look at this branch:

https://github.com/guoarthur/Kijiji-Repost-Headless/tree/json-attributes

Let me know.
