### ISSUE TITLE
category ID 668 Error

### ISSUE THREAD

**Issue by nbm077** [guoarthur/Kijiji-Repost-Headless#42]
for some reason posting to this category does not work

how to recreate error:
generate item to go in sporting goods excersize > watersports
try to post item 

example item.inf

postAdForm.geocodeLat=51.1254463
postAdForm.geocodeLng=-114.0734201
postAdForm.city=Calgary
postAdForm.addressCity=Calgary
postAdForm.province=AB
postAdForm.addressProvince=AB
postAdForm.postalCode=T3K 3V9
postAdForm.addressPostalCode=T3K 3V9
PostalLat=51.1254463
PostalLng=-114.0734201
categoryId=668
postAdForm.adType=OFFER
postAdForm.priceType=FIXED
postAdForm.priceAmount=10
postAdForm.attributeMap[forsaleby_s]=ownr
postAdForm.title=Scuba Gear
postAdForm.description=Scuba Gear good quality 
postAdForm.locationId=1700199
locationLevel0=9003
featuresForm.topAdDuration=7
submitType=saveAndCheckout
imageCsv=scuba.jpg

https://www.pastiebin.com/5999e61b4346f
here is kijiji error output txt generated

**Comment by justinwrightit** [comment]
I tried your inf file, ad posted with no problems.

Try manually posting the ad on the kijiji website, if you're getting the following popup you were given some form of ban.
![image](https://user-images.githubusercontent.com/23126640/29540649-9f30b414-869d-11e7-9bf0-38dd7c07433f.png)

When it happens to me I just swap out the user and lower the repost frequency.

**Comment by guoarthur** [comment]
Just out of curiosity, how often are you two reposting? When I used this before, I did about once a day and I never got banned.

**Comment by justinwrightit** [comment]
4/day never been banned, both users I upped to 6/day got banned so they're going back down to 4 now.
![image](https://user-images.githubusercontent.com/23126640/29540916-fc069a40-869e-11e7-852b-ed31300e52e0.png)

**Comment by justinwrightit** [comment]
#43

**Comment by nbm077** [comment]
im not banned.  i created the snorkle equipment under a different heading in swimming category and it posted.  it seemed to be a trouble just eith this category.  i also found another category with problem the fan and lights category.  and its not from reposting.  i only posted it once.  once i found a category workinf i setup reposting and you can repost as many times as allowed , 30 to 40 a day i believe?

**Comment by nbm077** [comment]
oh it could be a category limitation?  i will next time try to post manually and see if its dome form as ban, thanks justin
