### ISSUE TITLE
what's the best way to get the ad_id

### ISSUE THREAD

**Issue by vesper8** [guoarthur/Kijiji-Repost-Headless#44]
I'm building a cms on top of this and I'm currently struggling to find the best way to get the ad id back after creating a new ad

I need this in order to be able to delete it and perhaps track it over time or confirm it's status

i'm sure this is something others have had to do.. ideally if the script could output the ID after posting/reposting an ad that would be great as I could capture it and store it in my db

**Comment by guoarthur** [comment]
Are you writing a CMS around KijijiApi or KijijiCmd? If it's the former,
then the post_ad_using_data should already be returning the adId.

When I made the KijijiApi class, I was intending it to work with other non
command line interfaces as well (such as a Facebook bot or web interface).
I think this class would serve well as a base for a CMS.

If you want to use KijijiCmd, I could help you in making some modifications
to get out the adId? This file is basically a command line interface that
just makes calls to KijijiApi methods.

**Comment by vesper8** [comment]
sometimes all one needs to open up a file and go 'ooooh.. woow! awesome!!' is asking a question! I hadn't even bothered to open neither of your python files yet.. silly me.. now that I'm seeing all you've done.. I see how much more versatile and powerful this can be! Maybe it would help to mention all that added functionality available in the readme! sometimes we wrongfully assume the only method calls are the ones briefly mentioned in the examples.. I'm guilty of that a lot

great work btw!! i'm just a few hours in to this project but I see some cool things ahead now

**Comment by vesper8** [comment]
it would be cool if the presence of a login.inf in the directory with the cmd and api files would cause it to be used by default if you try to call `python kijiji_cmd.py show` without specifying the username and pw

**Comment by vesper8** [comment]
I changed it on mine so it works like this

```
def get_api(args):
    """
    For all commands except posting folder
    If no username or password passed then check for the presence of login.inf
    """

    api = kijiji_api.KijijiApi()

    if args.username is None:
        cred_file = "login.inf"
        creds = [line.strip() for line in open(cred_file, 'r')]
        args.username = creds[0]
        args.password = creds[1]

    api.login(args.username, args.password)

    return api

def nuke(args):
    """
    Delete all ads
    """
    api = get_api(args)
    allAds = api.get_all_ads()
    [api.delete_ad(adId) for adName, adId in allAds]
```

What do you think? I find it simpler to only initiate the api and do the login in one function

**Comment by jackm** [comment]
@vesper8 I too was working on implementing the feature where if no username/password was supplied via arguments, then it would attempt to use a global login.inf file in the root directory if that existed.

The test for this condition could either be put in the main function during initialization, or using a wrapper function like you made whenever the call to the KijijiApi class is done.

**Comment by nbm077** [comment]
it would be nice if that show would take login/passwords as many as you put into the login.inf, or be able to specify  a directory like, item1/login.inf when executed,., 

python kijiji_reposter show item1/login.inf
