### ISSUE TITLE
recommended proxy rotation to avoid getting blacklisted?

### ISSUE THREAD

**Issue by vesper8** [guoarthur/Kijiji-Repost-Headless#47]
I know this is a bit out of scope but just thought I'd ask to see if maybe you're already aware of something that works well for this purpose

basically i'm going to be doing a lot of queries from a single server with static ip and want to avoid getting blacklisted. Can you recommend a service and a package (in python I imagine) that would wrap your kijiji-repost-headless well and easily?

thanks!!

**Comment by vipertemp** [comment]
My favorite part is when kijiji gets sick and tired of all these people abusing their API and either shuts it down for everyone or tightens posting restrictions such that the API becomes almost completely worthless to non-corporate users.

**Comment by guoarthur** [comment]
What you're looking for is not in the best interest for the future success and continuation of this project. I do not support using proxies to get around Kijiji blacklists.

**Comment by vesper8** [comment]
I think you guys may have assumed I was planning on hammering and being malicious which is as far from reality as it could be. I was mostly interested in learning something new and thinking ahead when I offer to let my friends and family use this tool I'm building. I'm not aware of how strict they are when it comes to posting with this kind of script but I just figured it would be nice to make it a little harder for them to detect this behaviour. I never intended to do stupid things like hammer or post/query more than is sensible.

thanks for the continued good work

**Comment by vipertemp** [comment]
I'm still trying to figure out what's in it for them to allow access via an API. With more and more people wanting to use it I can only imagine posting limits being reduced and more restrictions being applied.

Convince me otherwise?

**Comment by vesper8** [comment]
the answer to that is simple... there is no API. This package IS the API.. and the number of people using this or other posting services must be a grain in the sand in their overall usage

**Comment by guoarthur** [comment]
I do not support using proxies for this project, and do not wish to support proxies. If you wish to develop this feature, please do so on your own fork.
